### ISSUE TITLE
RegExp matching error

### ISSUE THREAD

**Issue by Owsiana** [pbojan/cryptocoins-desklet-windows#8]
All skins stopped working. The log file shows the RegExp error:

```
NOTE (21:25:41.794) pbojan\CryptoCoins\Bitcoin\Bitcoin.ini: Refreshing skin
NOTE (21:25:41.875) pbojan\CryptoCoins\Cardano\Cardano.ini: Refreshing skin
ERRO (21:25:41.892) pbojan\CryptoCoins\Bitcoin\Bitcoin.ini - [MeasureCoinData]: RegExp matching error (-1)
NOTE (21:25:41.951) pbojan\CryptoCoins\Etherium\Ethereum.ini: Refreshing skin
ERRO (21:25:41.972) pbojan\CryptoCoins\Cardano\Cardano.ini - [MeasureCoinData]: RegExp matching error (-1)
ERRO (21:25:42.030) pbojan\CryptoCoins\Etherium\Ethereum.ini - [MeasureCoinData]: RegExp matching error (-1)
```

**Comment by ScytheFG** [comment]
I am experiencing the same issue, hopefully this can be an easy fix.
Currently everything is down!

**Comment by jbob23** [comment]
I'm experiencing it as well. Updated Rainmeter to latest, still receiving this in the log:
```
ERRO (09:52:17.371) pbojan\CryptoCoins\Litecoin\Litecoin.ini - [MeasureCoinData]: RegExp matching error (-1)
ERRO (09:52:17.376) : Script: scripts/Helpers.lua:100: field 'day' missing in date table
ERRO (09:52:17.376) : Script: scripts/Helpers.lua:100: field 'day' missing in date table
NOTE (09:52:19.668) pbojan\CryptoCoins\Litecoin\Litecoin.ini: Refreshing skin
ERRO (09:52:19.713) pbojan\CryptoCoins\Litecoin\Litecoin.ini - [MeasureCoinData]: RegExp matching error (-1)
ERRO (09:52:19.714) : Script: scripts/Helpers.lua:100: field 'day' missing in date table
ERRO (09:52:19.714) : Script: scripts/Helpers.lua:100: field 'day' missing in date table
```

**Comment by AsPeeK29** [comment]
Same problem ... Rainmeter uptodate and receiving this in the log too :

![image](https://user-images.githubusercontent.com/89927009/131695899-d5e4675d-d876-444a-bab9-2e234e4e39de.png)

**Comment by PrinzValium80** [comment]
Unfortunately i have the same problem.

**Comment by jaymedavis** [comment]
Looks like a problem with CoinMarketCap.  In their [Quick Start Guide](https://coinmarketcap.com/api/documentation/v1/#section/Quick-Start-Guide), they have a sample CURL request:

replace the api key with your own:
```
curl -H "X-CMC_PRO_API_KEY: b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c" -H "Accept: application/json" -d "start=1&limit=5000&convert=USD" -G https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
```
Try this for yourself (online [here](https://reqbin.com/curl)), and you will get 
```
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```

This same endpoint is used in Helpers.lua on this project.  Once CoinMarketCap fixes this on their end, our favorite Rainmeter plugin should start working again. 👍

**Comment by AsPeeK29** [comment]
I found that at https://status.coinmarketcap.com : 

Sep 1, 2021
API Authentication Issues
Resolved - The issue is now resolved. All API authentication should be back to normal status.
Sep 1, 18:24 UTC
Identified - If you are continuing to have key validation issues (1020 or 403 errors), as a temporary workaround, please ensure that all requests to our API include a user agent string. Our engineers are continuing to work on the underlying cause for this error.
Sep 1, 17:54 UTC
Investigating - There are currently key authentication issues that may result in 403 and 1020 errors when accessing the API. The engineering team is investigating and we will be posting updates here, as soon as we have them.
Sep 1, 16:31 UTC

**Comment by jaymedavis** [comment]
Thanks @AsPeeK29.

I submitted a bug to coinmarketcap.  The page linked makes me believe they think this is resolved.?

**Comment by jbob23** [comment]
Good find @jaymedavis & @AsPeeK29 looks like their sandbox is responding with 404 as well.

**Comment by jbob23** [comment]
I talked with coinmarketcap's API support, it appears that the API is working, and I've been able to send curl requests, just not through reqbin.com/curl as there is a switch in that test command that is unsupported on reqbin (-G) 
When running locally through a curl.exe, I'm able to get a response with pulled data and I'm able to look on my coinmarketcap's API usage and see the requested pull for data. When using the helpers.lua/specific coin ini  file, I see zero attempt made on my coinmarketcap's API dashboard.

**Comment by jaymedavis** [comment]
Awesome - confirmed @jbob23 - thanks.  I would expect this plugin to be working again... but it's still not for me.  Is it just me?

**Comment by pbojan** [comment]
Thank you all for the great investigation and finding the issue! Can someone confirm that the issue is resolved so I can close it as I am not near a Windows machine?

**Comment by PrinzValium80** [comment]
Hi,
My Widgets are still not working on Windows. 
I did not change anything.

**Comment by pbojan** [comment]
Just released a new version that solves the issue! Feel free to download it from: https://github.com/pbojan/cryptocoins-desklet-windows/releases/tag/v1.5 

Cheers! 🥳

**Comment by PrinzValium80** [comment]
Hi,
Yes, works again with the new version.
Thanks Man!
P.S. Be careful, installing the new version will overwrite all existing entries

**Comment by jestith** [comment]
Yes, working here, too. Thanks for all your efforts!
